apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      dummy: web
  template:
    metadata:
      labels:
        dummy: web
    spec:
      containers:
      - name: dummy-containers
        image: dmltjq2524/dummy-go:0.0.1
        args: [ "--kubelet-insecure-tls" ]
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: default
spec:
  type: NodePort
  selector:
    dummy: web
  ports:
    - port: 9999
      name: port01
      targetPort: 9999
      nodePort: 30001  
