apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy2-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      dummy2: web
  template:
    metadata:
      labels:
        dummy2: web
    spec:
      containers:
      - name: dummy2-containers
        image: dmltjq2524/dummy-go2:0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: dummy2-service
  namespace: default
spec:
  type: NodePort
  selector:
    dummy2: web
  ports:
    - port: 9998
      name: port02
      targetPort: 9998
      nodePort: 30002